name: Check Work Item Approval

on:
  pull_request:
    branches: [ "main" ]
    types: [ "opened", "reopened" ]
  workflow_dispatch:
jobs:
  check-work-item-approval:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
      - name: Check Work Item Approval
        run: ./check-work-item-approval
        env:
          JIRA_URL: https://one-atlas-qxfz.atlassian.net/
          JIRA_API_TOKEN: ${{ secrets.API_TOKEN }}
          JIRA_USERNAME: mkelly@mumosystems.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
